# Dockerfile.dev
FROM ruby:3.1.6-slim

# Install dependencies necessary for development
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      curl \
      nodejs \
      yarn \
      build-essential \
      default-libmysqlclient-dev && \
    rm -rf /var/lib/apt/lists/*

    
# Set the working directory to /app (you can adjust to match your project structure)
WORKDIR /app

# Set the Rails environment to development
ENV RAILS_ENV=development

# Copy Gemfile and Gemfile.lock first for caching bundle installs
COPY Gemfile Gemfile.lock ./

# Install gems
RUN bundle install

# Copy the rest of the application code
COPY . .

# Expose port 3000
EXPOSE 3000

# Start the Rails server, binding to all interfaces and staying in the foreground
CMD  ["/bin/sh", "-c", "rm -f /app/tmp/pids/server.pid && ./bin/rails server -b 0.0.0.0"]
